baseurl = "https://itslab-kyushu.github.io/youtube-comment-crawler/"
languageCode = "en-us"
metadataformat = "yaml"
title = "YouTube Comment Crawler"
theme = "hugo-alabaster-theme"

disqusShortname = ""
googleAnalytics = "UA-89247555-1"

[params]
	name = "YouTube Comment Crawler"
	description = "Scraping trending video page every day and comments posted to those videos every 30 mins."

	github_user   = "itslab-kyushu"
	github_repo   = "youtube-comment-crawler"
	github_banner = true

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

[params.sidebar]
	logo = "favicon.ico"

	github_button  = true
	travis_button  = false
	codecov_button = false
	gratipay = "~jkawamoto"

	show_relations = false

[params.footer]
	copyright = "[Junpei Kawamoto](https://github.com/jkawamoto/) | Icon by [Clipart Kid](http://www.clipartkid.com/)"
	show_powered_by = true
